name: weather_app
description: Live Weather and Weather Forecast
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: null
  connectivity: ^0.4.6+2
  cupertino_icons: ^0.1.2
  equatable: ^1.2.5
  firebase_auth: ^0.14.0
  flutter_icons: ^1.0.0+1
  flutter_spinkit: ^4.1.1
  fluttertoast: ^7.1.1
  google_sign_in: null
  http: ^0.12.0+3
  intl: ^0.16.0
  location: ^2.3.5
  open_settings: ^1.0.2
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
